/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.Checkbox;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author lmart
 */
public class jfAsistencia extends javax.swing.JFrame {
    Statement stm=null;
    Conexion conex = new Conexion();
    Connection conn = (Connection) conex.realizarConexion();

    /**
     * Creates new form jfAsistencia
     */
    public jfAsistencia() {
        initComponents();
        llenarTabla("");
        llenarTablaAsistenciaPasada("");
        JOptionPane.showMessageDialog(null, "No olvide seleccionar el curso para la asistencia", "Asistencia", JOptionPane.INFORMATION_MESSAGE);
        
        
        
        
        
    }
    public void llenarTabla(String sql){
        DefaultTableModel model = new DefaultTableModel();
        jTableAsistencia.setModel(model);
        
        
        model.addColumn("Rut");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Asistencia");
        addCheckedBox(3,jTableAsistencia);
        try{
            String cons = "";
            if (sql.equals("")){
               cons = "SELECT * FROM estudiante, cursos,matriculas WHERE matriculas.cod_curso = cursos.cod_curso AND matriculas.rut_estudiante = estudiante.rut_estudiante"; 
            }else{
                cons = sql;
            }
            //String sql = "SELECT * FROM estudiante, cursos, matriculas WHERE matriculas.cod_curso = cursos.cod_curso AND matriculas.rut_estudiante = estudiante.rut_estudiante";
            String[] datos = new String[3];
            stm = conn.createStatement();
            ResultSet res = stm.executeQuery(cons);
            while(res.next()){
                model.addRow(new Object []{
                    res.getString("rut_estudiante"),res.getString("nombres"),res.getString("apellidos")
                });
            }
            jTableAsistencia.setModel(model);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al Cargar la Lista "+ex, "Error de Carga", JOptionPane.ERROR_MESSAGE);
        }
        try{
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            String sql2 = "SELECT nombre FROM cursos";
            stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql2);
            while (rs.next()) {
                modelo.addElement(rs.getString("nombre"));
                cbCurso.setModel(modelo);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al Cargar los Cursos "+ex, "Error de Carga", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsistencia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        cmdAsistencia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbTipoDia = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAsistenciaPasada = new javax.swing.JTable();
        cbCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1039, 417));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Asistencia");

        cmdAtras.setText("Atras");
        cmdAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAtrasActionPerformed(evt);
            }
        });

        jTableAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAsistencia);

        jLabel2.setText("Curso");

        jLabel3.setText("Fecha:");

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel7.setText("Busqueda:");

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });

        btnBusqueda.setText("Buscar");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        cmdAsistencia.setText("Pasar Asistencia");
        cmdAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsistenciaActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo Dia:");

        cbTipoDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habil", "No habil" }));

        jTableAsistenciaPasada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAsistenciaPasada);

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCursoMouseClicked(evt);
            }
        });
        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdAsistencia)
                                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusqueda))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbTipoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(cmdAsistencia))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmdAtras))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void llenarTablaAsistenciaPasada(String sql){
        DefaultTableModel model = new DefaultTableModel();
        jTableAsistenciaPasada.setModel(model);
        
        
        model.addColumn("Rut");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Fecha");
        model.addColumn("Asistencia");
        model.addColumn("");
        addCheckedBox(5,jTableAsistenciaPasada);
        //Checkbox checkbox1 = new Checkbox();
        
        try{
            String cons = "";
            if (sql.equals("")){
                cons = "SELECT * FROM estudiante, asistencia WHERE estudiante.rut_estudiante = asistencia.rut_estudiante"; 
            }else{
                cons = sql;
            }
            stm = conn.createStatement();
            ResultSet res = stm.executeQuery(cons);
            while(res.next()){
                model.addRow(new Object []{
                    res.getString("rut_estudiante"),res.getString("nombres"),res.getString("apellidos"),res.getDate("fecha"),res.getString("estado"),
                    
                });
                if("estado".equals("Presente")){
                    addCheckedBox(5,jTableAsistenciaPasada);
                }
            }
            jTableAsistenciaPasada.setModel(model);
        }catch(SQLException ex){
            
        }
        
    }
    //Funcion para crear un checkbox en cualquier lado pero no funcion elsetSelected
    //public Checkbox chekbox1 = new Checkbox().setSelected(true);
    
    public void addCheckedBox(int column, JTable table){
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    private void cmdAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAtrasActionPerformed
        dispose();
    }//GEN-LAST:event_cmdAtrasActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        /*String busqueda = txtBusqueda.getText().trim();

        String sql = "SELECT * FROM estudiante WHERE estudiante.nombres LIKE '%"+busqueda+"%'";

        llenarTabla(sql);*/
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void cmdAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsistenciaActionPerformed
        
        for (int i = 0; i<jTableAsistencia.getRowCount();i++){
            //Trozo de codigo sacado del if de abajo jTableAsistencia.getSelectedRow()>=0 && 
            /*Boolean check = false;
            if(isSelected(i,3,jTableAsistencia)){
                check = true;
            }else{
                check = false;
            }*/
            //System.out.println("Pasada numero :"+i);
            if(isSelected(i,3,jTableAsistencia)){
                //try{
                    //Obtencion de los datos (INICIO)
                    DefaultTableModel tm = (DefaultTableModel)jTableAsistencia.getModel();
                    String estado = "";
                
                    String rut = String.valueOf(tm.getValueAt(jTableAsistencia.getSelectedRow(),0));
                    String nombre = String.valueOf(tm.getValueAt(jTableAsistencia.getSelectedRow(),1));
                    String apellido = String.valueOf(tm.getValueAt(jTableAsistencia.getSelectedRow(),2));
                    //Date fecha = jDateChooser1;
                    SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
                    String fecha =  format1.format(jDateChooser1.getDate());
                    String tipo_dia = (String)cbTipoDia.getSelectedItem();
                    //Obtencion de datos (FINAL)
                    estado = "Presente";
                    //Insertado de datos (INICIO)
                    try{
                        String inser = "INSERT INTO asistencia(fecha,rut_estudiante,estado,tipo_dia) VALUES ('"+fecha+"','"+rut+"','"+estado+"','"+tipo_dia+"')";
                        Statement stm = conn.createStatement();
                        stm.executeUpdate(inser);
                        JOptionPane.showMessageDialog(null, "Asistencia Pasada","Ingreso",1);
                    }catch(SQLException ei){
                        JOptionPane.showMessageDialog(null, "Error al pasar asistencia"+ei,"Insert",3);
                    }
                    //Insertado de datos (FINAL)
                    //System.out.println("Salida de try presente");
                /*}catch(Exception ei){
                    JOptionPane.showMessageDialog(null, "Error al procesar asistencia"+ei,"Insert",3);
                }*/
            }else{
                //try{
                    System.out.println("Ingreso al try de ausente");
                    //Obtencion de los datos (INICIO)
                    DefaultTableModel tm = (DefaultTableModel)jTableAsistencia.getModel();
                    String estado = "";
                
                    String rut = String.valueOf(tm.getValueAt(jTableAsistencia.getSelectedRow(),0));
                    String nombre = String.valueOf(tm.getValueAt(jTableAsistencia.getSelectedRow(),1));
                    String apellido = String.valueOf(tm.getValueAt(jTableAsistencia.getSelectedRow(),2));
                    //Date fecha = jDateChooser1;
                    SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
                    String fecha =  format1.format(jDateChooser1.getDate());
                    
                    String tipo_dia = (String)cbTipoDia.getSelectedItem();
                    //Obtencion de datos (FINAL)
                    
                    estado = "Ausente";
                    //Insertado de datos (INICIO)
                    try{
                        String inser = "INSERT INTO asistencia(fecha,rut_estudiante,estado,tipo_dia) VALUES ('"+fecha+"','"+rut+"','"+estado+"','"+tipo_dia+"')";
                        Statement stm = conn.createStatement();
                        stm.executeUpdate(inser);
                        JOptionPane.showMessageDialog(null, "Asistencia Pasada","Ingreso",1);
                    }catch(SQLException ei){
                        JOptionPane.showMessageDialog(null, "Error al pasar asistencia"+ei,"Insert",3);
                    }
                    //Insertado de datos (FINAL)
                /*}catch(Exception ei){
                    JOptionPane.showMessageDialog(null, "Error al procesar asistencia"+ei,"Insert",3);
                }*/
            }
        }
        llenarTablaAsistenciaPasada("");
    }//GEN-LAST:event_cmdAsistenciaActionPerformed

    
    private void cbCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCursoMouseClicked
        //System.out.println("Clickeado");
        String curso = (String)cbCurso.getSelectedItem();
        llenarTablaAsistenciaFiltrado(curso);
    }//GEN-LAST:event_cbCursoMouseClicked

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCursoActionPerformed
    
    public boolean isSelected(int row, int column, JTable table){
        return table.getValueAt(row,column) != null;
    }
    
    public void llenarTablaAsistenciaFiltrado(String curso){
        Integer cursoDB = Integer.valueOf(obtenerCodigoCurso(curso));
        
        String sql = "SELECT * FROM matriculas,estudiante,cursos WHERE matriculas.cod_curso LIKE '%"+cursoDB+"%' AND matriculas.rut_estudiante = estudiante.rut_estudiante AND matriculas.cod_curso = cursos.cod_curso";
        
        llenarTabla(sql);
    }
    /*public void llenarTablaAsistenciaPasadaFiltrado(String curso){
        Integer cursoDB = Integer.valueOf(obtenerCodigoCurso(curso));
        
        String sql = "SELECT * FROM estudiante, asistencia WHERE estudiante.rut_estudiante = asistencia.rut_estudiante"; 
        
        llenarTablaAsistenciaPasada(sql);
    }*/
    public String obtenerCodigoCurso(String curso){
        String codcurso = "";
        try{
            String sql = "SELECT cod_curso FROM cursos WHERE cursos.nombre = '"+curso+"'";
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            
            if (rs.next()){
                codcurso = rs.getString("cod_curso");
            }else{
                codcurso = "";
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"ERROR AL SELECCIONAR EL CURSO","SISTEMA",JOptionPane.WARNING_MESSAGE);
        }
        return codcurso;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbTipoDia;
    private javax.swing.JButton cmdAsistencia;
    private javax.swing.JButton cmdAtras;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAsistencia;
    private javax.swing.JTable jTableAsistenciaPasada;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
